#!/command/with-contenv sh
# Prismarr — initialization script, runs ONCE at container startup, before
# frankenphp and messenger-worker (s6 oneshot dependency).
#
# Responsibilities:
#   1. Ensure the var/data directory (volume mount) is writable.
#   2. Generate a .env.local with random secrets on first boot, persisted
#      in the volume so it survives image rebuilds.
#   3. Create the SQLite schema if the database is empty.
#
# Idempotent: safe to run on every boot, only acts when needed.

set -e

APP_DIR="/var/www/html"
DATA_DIR="$APP_DIR/var/data"
ENV_STORED="$DATA_DIR/.env.local"
ENV_LINK="$APP_DIR/.env.local"
DB_FILE="$DATA_DIR/prismarr.db"

PRISMARR_VERSION="${PRISMARR_VERSION:-1.0.0-dev}"
PRISMARR_PORT="${PRISMARR_PORT:-7070}"
APP_ENV="${APP_ENV:-prod}"

# Status flags (populated during the run, printed in the summary)
secrets_action="already configured"
schema_action="already up to date"
tz_action="UTC (default, no \$TZ set)"

# ── 0. Time zone propagation ───────────────────────────────────────────────
# Issue #12 — honor the user's TZ env var (e.g. TZ=Pacific/Honolulu in
# docker-compose). Two layers: the OS clock (used by `date`, file mtimes,
# log timestamps from FrankenPHP) and PHP's date.timezone (used by Twig
# helpers, /admin/settings server time, calendar). php.ini ships UTC as a
# safe default; we drop a higher-priority zz-tz.ini here so PHP picks up
# the user's zone without us editing the base ini.
if [ -n "$TZ" ] && [ -f "/usr/share/zoneinfo/$TZ" ]; then
  cp "/usr/share/zoneinfo/$TZ" /etc/localtime
  echo "$TZ" > /etc/timezone
  echo "date.timezone = $TZ" > /usr/local/etc/php/conf.d/zz-tz.ini
  tz_action="$TZ"
elif [ -n "$TZ" ]; then
  tz_action="invalid \$TZ='$TZ' — falling back to UTC"
fi

# ── 0b. PHP runtime overrides ──────────────────────────────────────────────
# Issue #13 — let homelabs with very large libraries bump memory and time
# limits via docker-compose env vars instead of mounting a custom ini. Both
# default to whatever php.ini ships (currently 1024M / 120s); set them only
# if the user opted in. The "zz-" prefix loads after prismarr.ini so the
# values override the baked-in defaults.
runtime_action="defaults (1024M / 120s)"
runtime_ini="/usr/local/etc/php/conf.d/zz-runtime.ini"
: > "$runtime_ini"  # truncate any previous boot's content
if [ -n "$PHP_MEMORY_LIMIT" ]; then
  echo "memory_limit = $PHP_MEMORY_LIMIT" >> "$runtime_ini"
  runtime_action="memory_limit=$PHP_MEMORY_LIMIT"
fi
if [ -n "$PHP_MAX_EXECUTION_TIME" ]; then
  echo "max_execution_time = $PHP_MAX_EXECUTION_TIME" >> "$runtime_ini"
  runtime_action="${runtime_action} max_execution_time=${PHP_MAX_EXECUTION_TIME}s"
fi

# ── 1. Writable volume ──────────────────────────────────────────────────────
# var/caddy = HOME of the FrankenPHP process (XDG data store, autosave files).
mkdir -p "$DATA_DIR" "$DATA_DIR/sessions" "$APP_DIR/var/cache" "$APP_DIR/var/log" "$APP_DIR/var/caddy"
chown -R www-data:www-data "$APP_DIR/var"

# ── 2. Secrets generation on first boot ─────────────────────────────────────
if [ ! -f "$ENV_STORED" ]; then
  APP_SECRET=$(openssl rand -hex 32)
  MERCURE_JWT_SECRET=$(openssl rand -hex 32)

  cat > "$ENV_STORED" <<EOF
# Secrets auto-generated by Prismarr's init script on first boot.
# Persisted in the prismarr_data volume. Do not commit, do not edit manually
# unless you want to rotate them.

APP_SECRET=$APP_SECRET
MERCURE_JWT_SECRET=$MERCURE_JWT_SECRET
EOF

  chown www-data:www-data "$ENV_STORED"
  chmod 600 "$ENV_STORED"
  secrets_action="generated"
fi

# Symlink .env.local → volume if nothing exists at the project root
# (dev bind-mount may already provide a real file, respect it).
if [ ! -e "$ENV_LINK" ]; then
  ln -s "$ENV_STORED" "$ENV_LINK"
fi

# ── 3. Database schema + migrations ─────────────────────────────────────────
# Runs every boot. On first boot: creates the DB file and applies all
# migrations (baseline + any later ones). On subsequent boots: applies
# only migrations released since the last boot, or no-op if up to date.
cd "$APP_DIR"
if [ ! -f "$DB_FILE" ] || [ ! -s "$DB_FILE" ]; then
  schema_action="creating database + applying migrations"
else
  schema_action="migrations up to date"
fi
migrate_output=$(php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration 2>&1)
if echo "$migrate_output" | grep -qE "Migrating up to|executed"; then
  schema_action="migrations applied"
fi
chown www-data:www-data "$DB_FILE" 2>/dev/null || true

# Migrations run in root context (s6 init / PID 1). Symfony resolves the
# Doctrine ORM parser cache while parsing the migration query, which
# pre-creates the cache pool directories under var/cache/prod/pools/system/
# owned by root. Once frankenphp and messenger-worker drop to www-data,
# they can't write back into those pools and every request spams a
# "Permission denied" warning. Catch-all recursive chown fixes that.
chown -R www-data:www-data "$APP_DIR/var" 2>/dev/null || true

# ── Startup banner ──────────────────────────────────────────────────────────
cat <<BANNER

╭──────────────────────────────────────────────────────────────╮
│                                                              │
│      ██████╗ ██████╗ ██╗███████╗███╗   ███╗ █████╗ ██████╗   │
│      ██╔══██╗██╔══██╗██║██╔════╝████╗ ████║██╔══██╗██╔══██╗  │
│      ██████╔╝██████╔╝██║███████╗██╔████╔██║███████║██████╔╝  │
│      ██╔═══╝ ██╔══██╗██║╚════██║██║╚██╔╝██║██╔══██║██╔══██╗  │
│      ██║     ██║  ██║██║███████║██║ ╚═╝ ██║██║  ██║██║  ██║  │
│      ╚═╝     ╚═╝  ╚═╝╚═╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝  │
│                                                              │
│              Self-hosted media stack dashboard               │
│                                                              │
╰──────────────────────────────────────────────────────────────╯

  Version        : $PRISMARR_VERSION
  Environment    : $APP_ENV
  Listening on   : http://0.0.0.0:$PRISMARR_PORT
  Database       : $DB_FILE
  Secrets file   : $ENV_STORED

  Boot checks
  ──────────────────────────────────────────────────────────
  [ok] Secrets                $secrets_action
  [ok] Database schema        $schema_action
  [ok] Time zone              $tz_action
  [ok] PHP limits             $runtime_action

  Ready — open http://localhost:$PRISMARR_PORT to access the UI.
  If this is a first install, you will be redirected to the
  setup wizard to create your admin account and configure
  your services (Radarr, Sonarr, qBittorrent, ...).

BANNER
